### ISSUE TITLE
cannot import name 'DEFAULT_CIPHERS' with urllib3 >= 2.0

### ISSUE THREAD

**Issue by c0eos** [Language-Tools/anki-hyper-tts#116]
```
Error
An add-on you installed failed to load. If problems persist, please go to the Tools>Add-ons menu, and disable or delete the add-on.

When loading '⁨HyperTTS - Add speech to your flashcards⁩':
⁨Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/aqt/addons.py", line 246, in loadAddons
    __import__(addon.dir_name)
  File "/home/user/.local/share/Anki2/addons21/111623432/__init__.py", line 142, in <module>
    service_manager.init_services()
  File "/home/user/.local/share/Anki2/addons21/111623432/servicemanager.py", line 87, in init_services
    self.import_services()
  File "/home/user/.local/share/Anki2/addons21/111623432/servicemanager.py", line 96, in import_services
    __import__(self.package_name, globals(), locals(), [module_name], sys._addon_import_level_base)
  File "/home/user/.local/share/Anki2/addons21/111623432/services/service_amazon.py", line 5, in <module>
    import boto3
  File "/home/user/.local/share/Anki2/addons21/111623432/external/boto3/__init__.py", line 16, in <module>
    from boto3.session import Session
  File "/home/user/.local/share/Anki2/addons21/111623432/external/boto3/session.py", line 17, in <module>
    import botocore.session
  File "/home/user/.local/share/Anki2/addons21/111623432/external/botocore/session.py", line 29, in <module>
    import botocore.credentials
  File "/home/user/.local/share/Anki2/addons21/111623432/external/botocore/credentials.py", line 35, in <module>
    from botocore.config import Config
  File "/home/user/.local/share/Anki2/addons21/111623432/external/botocore/config.py", line 16, in <module>
    from botocore.endpoint import DEFAULT_TIMEOUT, MAX_POOL_CONNECTIONS
  File "/home/user/.local/share/Anki2/addons21/111623432/external/botocore/endpoint.py", line 26, in <module>
    from botocore.httpsession import URLLib3Session
  File "/home/user/.local/share/Anki2/addons21/111623432/external/botocore/httpsession.py", line 10, in <module>
    from urllib3.util.ssl_ import (
ImportError: cannot import name 'DEFAULT_CIPHERS' from 'urllib3.util.ssl_' (/home/user/.local/lib/python3.11/site-packages/urllib3/util/ssl_.py)
```
⁩
According to [urllib3's migration guide](https://urllib3.readthedocs.io/en/latest/v2-migration-guide.html) , this is due to "Removed the default set of TLS ciphers, instead now urllib3 uses the list of ciphers configured by the system."

**Comment by luc-languagetools** [comment]
Which version of Anki do yo use?

**Comment by c0eos** [comment]
Version ⁨2.1.65 (141bc18b)⁩
Python 3.11.3 Qt 6.5.2 PyQt 6.5.2

**Comment by luc-languagetools** [comment]
OK how did you install anki ?

**Comment by c0eos** [comment]
Anki comes from the [AUR package anki](https://aur.archlinux.org/packages/anki).

**Comment by luc-languagetools** [comment]
OK. So if you have a workaround, please use that for now. With HyperTTS, I had to package boto3 die Amazon along with all dependencies. I may need to update urllib3.

**Comment by Fat-Zer** [comment]
Note that upstream botocore [fixed it][1] in 1.29.123. And also you shouldn't have to update urllib3: newer botocore should still support older urllib3 just fine.

PS: as another workaround you can apply couple of patches to `~/.local/share/Anki2/addons21/111623432/external/botocore/httpsession.py`:
- https://github.com/boto/botocore/commit/0a6d8e3c6325da395a04227599cfa292190d6841
- https://github.com/boto/botocore/commit/7b4c26e721936b185681cb10010ded4026295bd4

though, it will be overwritten by next hypertts update

[1]: https://github.com/boto/botocore/issues/2921

**Comment by arkhandir** [comment]
Same issue with Anki 2.1.66 beta 1, Python 3.9.15 Qt 6.5.0 PyQt 6.5.0, installed with the official binaries.

**Comment by luc-languagetools** [comment]
I'll try to package a newer version of boto3 for the next release. will also test with Anki 2.1.66 beta

**Comment by luc-languagetools** [comment]
Hi, I updated boto3 in HyperTTS 0.88, could you give it try and let me know ?
