### ISSUE TITLE
Stopped working after updating on 2023-08-07

### ISSUE THREAD

**Issue by GrzegorzDyrda** [Language-Tools/anki-hyper-tts#117]
Like in the title - it stopped working right after the update and Anki restart.
Now every time I launch Anki I get the following error:

```
Error
An add-on you installed failed to load. If problems persist, please go to the Tools>Add-ons menu, and disable or delete the add-on.

When loading '⁨HyperTTS - Add speech to your flashcards⁩':

Traceback (most recent call last):
  File "aqt.addons", line 246, in loadAddons
  File "/Users/xxx/Library/Application Support/Anki2/addons21/111623432/__init__.py", line 129, in <module>
    from . import hypertts
  File "/Users/xxx/Library/Application Support/Anki2/addons21/111623432/hypertts.py", line 24, in <module>
    config_models = __import__('config_models', globals(), locals(), [], sys._addon_import_level_base)
  File "/Users/xxx/Library/Application Support/Anki2/addons21/111623432/config_models.py", line 5, in <module>
    from pydantic import BaseModel, Field
  File "/Users/xxx/Library/Application Support/Anki2/addons21/111623432/external/pydantic/__init__.py", line 3, in <module>
    import pydantic_core
  File "/Users/xxx/Library/Application Support/Anki2/addons21/111623432/external/pydantic_core/__init__.py", line 6, in <module>
    from ._pydantic_core import (
ImportError: dlopen(/Users/xxx/Library/Application Support/Anki2/addons21/111623432/external/pydantic_core/_pydantic_core.cpython-39-darwin.so, 2): no suitable image found.  Did find:
	/Users/xxx/Library/Application Support/Anki2/addons21/111623432/external/pydantic_core/_pydantic_core.cpython-39-darwin.so: mach-o, but wrong architecture
	/Users/xxx/Library/Application Support/Anki2/addons21/111623432/external/pydantic_core/_pydantic_core.cpython-39-darwin.so: mach-o, but wrong architecture
```

Anki Version ⁨2.1.65 (aa9a734f)⁩
Python 3.9.15 Qt 6.5.0 PyQt 6.5.0
MacOS Big Sur 11.7.6

**Comment by luc-languagetools** [comment]
I've rolled back the problematic release, plus update HyperTTS and restart, apologies for the issue.

**Comment by GrzegorzDyrda** [comment]
No problem, thanks for a quick fix :) 👍
