### ISSUE TITLE
Anki 2.1.66  - no module called six

### ISSUE THREAD

**Issue by danieltomasz** [Language-Tools/anki-hyper-tts#121]
When starting Anki 2.1.66, I getting this error
```
Error
An add-on you installed failed to load. If problems persist, please go to the Tools>Add-ons menu, and disable or delete the add-on.

When loading '⁨HyperTTS - Add speech to your flashcards⁩':
⁨Traceback (most recent call last):
  File "aqt.addons", line 246, in loadAddons
  File "/Users/daniel/Library/Application Support/Anki2/addons21/111623432/__init__.py", line 142, in <module>
    service_manager.init_services()
  File "/Users/daniel/Library/Application Support/Anki2/addons21/111623432/servicemanager.py", line 87, in init_services
    self.import_services()
  File "/Users/daniel/Library/Application Support/Anki2/addons21/111623432/servicemanager.py", line 96, in import_services
    __import__(self.package_name, globals(), locals(), [module_name], sys._addon_import_level_base)
  File "/Users/daniel/Library/Application Support/Anki2/addons21/111623432/services/service_amazon.py", line 5, in <module>
    import boto3
  File "/Users/daniel/Library/Application Support/Anki2/addons21/111623432/external/boto3/__init__.py", line 16, in <module>
    from boto3.session import Session
  File "/Users/daniel/Library/Application Support/Anki2/addons21/111623432/external/boto3/session.py", line 17, in <module>
    import botocore.session
  File "/Users/daniel/Library/Application Support/Anki2/addons21/111623432/external/botocore/session.py", line 28, in <module>
    import botocore.configloader
  File "/Users/daniel/Library/Application Support/Anki2/addons21/111623432/external/botocore/configloader.py", line 19, in <module>
    from botocore.compat import six
  File "/Users/daniel/Library/Application Support/Anki2/addons21/111623432/external/botocore/compat.py", line 27, in <module>
    from dateutil.tz import tzlocal
  File "/Users/daniel/Library/Application Support/Anki2/addons21/111623432/external/dateutil/tz/__init__.py", line 2, in <module>
    from .tz import *
  File "/Users/daniel/Library/Application Support/Anki2/addons21/111623432/external/dateutil/tz/tz.py", line 19, in <module>
    import six
ModuleNotFoundError: No module named 'six'
⁩
```

on MacOS 14, Public beta 4

**Comment by luc-languagetools** [comment]
Thank you let me try to fix asap

**Comment by luc-languagetools** [comment]
Please update to HyperTTS 0.88 and let me know whether it works.

**Comment by danieltomasz** [comment]
There is no error now, I am closing this issue, thank you!
