### ISSUE TITLE
Connection bug

### ISSUE THREAD

**Issue by Casartellii** [Language-Tools/anki-hyper-tts#7]
It seems to be similiar with the connection issue I've reported on AwesomeTSS repository.

```
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.48 (fb07bad3) Python 3.8.6 Qt 5.14.2 PyQt 5.14.2
Platform: Windows 10
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2022-01-28 22:20:31

Caught exception:
Traceback (most recent call last):
  File "urllib3\connectionpool.py", line 699, in urlopen
  File "urllib3\connectionpool.py", line 382, in _make_request
  File "urllib3\connectionpool.py", line 1010, in _validate_conn
  File "urllib3\connection.py", line 411, in connect
  File "urllib3\util\ssl_.py", line 449, in ssl_wrap_socket
  File "urllib3\util\ssl_.py", line 493, in _ssl_wrap_socket_impl
  File "ssl.py", line 500, in wrap_socket
  File "ssl.py", line 1040, in _create
  File "ssl.py", line 1309, in do_handshake
ConnectionResetError: [WinError 10054] Foi forçado o cancelamento de uma conexão existente pelo host remoto

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "requests\adapters.py", line 439, in send
  File "urllib3\connectionpool.py", line 755, in urlopen
  File "urllib3\util\retry.py", line 532, in increment
  File "urllib3\packages\six.py", line 769, in reraise
  File "urllib3\connectionpool.py", line 699, in urlopen
  File "urllib3\connectionpool.py", line 382, in _make_request
  File "urllib3\connectionpool.py", line 1010, in _validate_conn
  File "urllib3\connection.py", line 411, in connect
  File "urllib3\util\ssl_.py", line 449, in ssl_wrap_socket
  File "urllib3\util\ssl_.py", line 493, in _ssl_wrap_socket_impl
  File "ssl.py", line 500, in wrap_socket
  File "ssl.py", line 1040, in _create
  File "ssl.py", line 1309, in do_handshake
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(10054, 'Foi forçado o cancelamento de uma conexão existente pelo host remoto', None, 10054, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Casartelli\AppData\Roaming\Anki2\addons21\111623432\component_voiceselection.py", line 266, in play_sample
    self.hypertts.play_sound(self.sample_text, selected_voice, options)
  File "C:\Users\Casartelli\AppData\Roaming\Anki2\addons21\111623432\hypertts.py", line 194, in play_sound
    full_filename, audio_filename = self.generate_audio_write_file(source_text, voice, options)
  File "C:\Users\Casartelli\AppData\Roaming\Anki2\addons21\111623432\hypertts.py", line 206, in generate_audio_write_file
    f.write(self.service_manager.get_tts_audio(source_text, voice, options))
  File "C:\Users\Casartelli\AppData\Roaming\Anki2\addons21\111623432\servicemanager.py", line 101, in get_tts_audio
    return self.cloudlanguagetools.get_tts_audio(source_text, voice, options)
  File "C:\Users\Casartelli\AppData\Roaming\Anki2\addons21\111623432\cloudlanguagetools.py", line 30, in get_tts_audio
    response = requests.post(full_url, json=data, headers={
  File "requests\api.py", line 119, in post
  File "requests\api.py", line 61, in request
  File "requests\sessions.py", line 542, in request
  File "requests\sessions.py", line 655, in send
  File "requests\adapters.py", line 498, in send
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(10054, 'Foi forçado o cancelamento de uma conexão existente pelo host remoto', None, 10054, None))

```

**Comment by luc-languagetools** [comment]
Are you using a VPN, a firewall, or some software that may restrict the connections that Anki makes ? Are you able to open this URL? https://cloud-language-tools-tts-prod.anki.study/language_data_v1

**Comment by Casartellii** [comment]
I'm using [Proton VPN](https://protonvpn.com/) and yes I'm able to open the URL.

**Comment by luc-languagetools** [comment]
And inside awesometts you're seeing the same issue? What about if you use your own Google cloud key?

**Comment by Casartellii** [comment]
I had this issue just a few times on awesometts, but I think my internet is the culprit because I was downloading some files and my connection was very slow. That was the case for this on Hypertss one too.

**Comment by luc-languagetools** [comment]
So you're able to user HyperTTS if you're not downloading anything else at the same time ?

**Comment by Casartellii** [comment]
Yeah, pretty much it. If I'm downloading some heavy file that bug tends to happen, if not, everything works just fine.
